# Generated by Django 5.2 on 2025-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_deck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
